### ISSUE TITLE
Duration property for tooltip

### ISSUE THREAD

**Issue by aytunch** [stargazing-dino/just_the_tooltip#10]
We should be able to set how long the tooltip will stay shown

**Comment by stargazing-dino** [comment]
I had a different need for my tooltips but I'll work on this for the v1.0.0 where I'll also add support for mouse as well

**Comment by stargazing-dino** [comment]
This should be good `0.0.4`. Try changing `showDuration` on the tooltip.

```dart
showDuration: Duration(seconds: 1),
```
