### ISSUE TITLE
Show and hide the tooltip with fade in/out animation

### ISSUE THREAD

**Issue by aytunch** [stargazing-dino/just_the_tooltip#11]
Right now it appears and disappears instantly and this does not look good

**Comment by stargazing-dino** [comment]
Can you add a video and or code to go along? I did something funny with the example code to make the gif but if it's not about that, can you add more information?

**Comment by stargazing-dino** [comment]
Totally mistunderstood this issue. Anyways, I already had the fade animation in place but just didn't have it hooked up. Should be good now in version `0.0.2+1`

9944b18e8e4ddb3ed187a9125c976270cd599d4d
