### ISSUE TITLE
How to add Hover

### ISSUE THREAD

**Issue by cgowthamanmca** [stargazing-dino/just_the_tooltip#16]
When I hover the button this tooltip need to show how to do this

**Comment by stargazing-dino** [comment]
I'm actually working on this now. My original use did not need hover but it's suprisingly easier than I thought. I'll have a new experimental version out later tomorrow at the earliest

**Comment by cgowthamanmca** [comment]
Thank you

**Comment by stargazing-dino** [comment]
Try version `0.0.4` and make sure you set the `isModal` property to `false` (the default). Docs are also slightly updated.
